### ISSUE TITLE
Processing Time

### ISSUE THREAD

**Issue by sapanshah** [immuta/bakula#10]
We will want to make sure that when we start a container that we capture the processing time.

**Comment by sapanshah** [comment]
We will want to use the containers docker-py call to keep track of container life time.

**Comment by ericjperry** [comment]
So, does that mean we're going to have something polling and calling the containers method? It looks like that is analogous to ```docker ps``` which just tells you what is currently running. I suppose we can pass the ```exited``` flag which will only show containers that have exited, but we still need to poll for that.

**Comment by sapanshah** [comment]
Yes, it looks like we will have to poll for the exited containers, since they are generally exiting when they are done. Lets look through the API as well a bit more, there might be a better way of doing this.

**Comment by ericjperry** [comment]
Assigning this to myself just because it's tightly coupled with the other metrics stuff that I'm working on.

**Comment by ericjperry** [comment]
Resolved by #10.
