### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by sapanshah** [immuta/bakula#17]
Add some sort of simple login logic.

**Comment by ericjperry** [comment]
I'm going to put together the service for auth/user creation that does the following:

* Stores user login information with the rest of the data via peewee
* Bootstraps the system with an initial user (an admin), allows that user to create other users. Not really worried about sophisticated permission management at this point, I'll just have one account that can create other accounts. We can deal with more complex stuff later
* Stores a hashed password (using bcrypt) in the db.
* Generates a random token for calling the API
* A bottle plugin/decorator for checking for a token.

Any thoughts? I found a bottle auth plugin called [Cork](http://cork.firelet.net/) but it doesn't support peewee (only SQLAlchemy). We could probably use that if we switch ORMs, but I could also probably write this all in a few hours. I'm going to start just rolling our own, if it looks like it's taking too long I may revisit using cork.

**Comment by sapanshah** [comment]
Any reason not to use the simple auth plugin system that we already have?

**Comment by KrisSiegel** [comment]
@sapanshah are you referring to what exists in BoData? Is that easy to lift up? If so we should probably use that. Otherwise this should be pretty easy to build after looking at the bottle API (though I'll admit I miss express and hapi a little bit here; I didn't see an easy way to decorate specific routes as requiring auth in bottle unless I missed it).

**Comment by ericjperry** [comment]
Yeah, @sapanshah do you want me to rip that out of BoData? The difference here is that I think our UI/client doesn't need a service (should just run in browser and hit our API), so it will work a little differently but I can probably use a bunch of the code.

**Comment by sapanshah** [comment]
Yeah worth ripping out that code if we can makes it easier. @KrisSiegel if you look at the code what I do is install the token plugin and then bottle automatically decorates all the routes with the requiring a token to login. I can also tell each route to skip using the plugin too.

**Comment by KrisSiegel** [comment]
Okay I totally didn't notice the auth plugin. Seems pretty simple! Still not as pretty as JavaScript :trollface:

**Comment by ericjperry** [comment]
I was able to copy a bunch of stuff from the BoData plugins and token generation (thanks Soup :smile:). I'm going to fix/add unit tests in the morning and I'll have a PR out probably before 10.
