### ISSUE TITLE
Reference Counting Files

### ISSUE THREAD

**Issue by sapanshah** [immuta/bakula#2]
Check to see how we would reference count a file. Do we want to use hard links, soft links, or just create an outbox?

**Comment by KrisSiegel** [comment]
So we discussed and we're going to use hard links.

So a docker container will be spun up with its own "inbox" (simply a folder on the host's file system for the specific container being spun up) that contains hard links back to the original files. The container will then operate on files within the inbox. When finished processing each file the container will mark it for deletion thusly deleting it in its inbox and original place if reference count hits 0 (just in case another container or someone else opens it). The container spins down and its life story is over shortly after it began.

I believe I captured that correctly; @sapanshah / @ericjperry?

**Comment by KrisSiegel** [comment]
Closing because we just talked about this in person.
