### ISSUE TITLE
Upload Event

### ISSUE THREAD

**Issue by sapanshah** [immuta/bakula#26]
Create an endpoint that is capable of uploading an event

it should get a topic message and a set of files which correspond to the event.

**Comment by ericjperry** [comment]
Not 100% sure what this means. So, this would be in the case that there is not some Generator/process pushing events on the topic?

**Comment by KrisSiegel** [comment]
This would just take the POST that a generator would hit, create a file representation for it and toss it in the master inbox.

**Comment by ericjperry** [comment]
Alright, gotcha. And this potentially supports a batch of events? Re:

> and a set of files which correspond to the event.

**Comment by KrisSiegel** [comment]
Sure? Sure!
