### ISSUE TITLE
Mounting a Fuse Filesystem in Docker

### ISSUE THREAD

**Issue by sapanshah** [immuta/bakula#3]
Check to see what would need to be done to mount a fuse filesystem into a docker container.

**Comment by ericjperry** [comment]
Created a docker container with all of the prototype stuff in it, via https://github.com/immuta/bodata-prototype/pull/74.

The docker container that mounts the filesystem must be run with the ```--privileged=true```.

The easiest way to test this stuff is to do the following:

* Log into our private docker registry with ```docker login https://registry.immuta.com```
* Pull the prototype image with ```docker pull registry.immuta.com/bodata-prototype```
* Start the prototype container with ```docker run --privileged=true -d -p 8080:8080 -p 4242:4242 registry.immuta.com/bodata-prototype /bin/sh -c "/bodata/server/bodata-server & /bodata/console/bodata-console"```. This will run the server and console.
* Hop on the container with ```docker exec -it <container ID> bash```
* Make a directory ```mkdir ~/bodata```
* Start the filesystem with ```/bodata/filesystem/bodata-filesystem``` (and point the mount at the /root/bodata directory)

**Comment by ericjperry** [comment]
@sapanshah @KrisSiegel See my above comment for guidance on using the docker image. I'll put this in a README somewhere but for now just reference this.
