### ISSUE TITLE
Update Bakula to default configuration parameters if no configuration is provided

### ISSUE THREAD

**Issue by ericjperry** [immuta/bakula#41]
Bakula should run an in-memory db if no configuration is provided. This might get a little weird once we tie in the docker registry (do we really want to have a hard-coded default username/password? probably not), but it would be useful. We probably need a way to handle not having the registry configured if the user doesn't have credentials (since we aren't going to put the creds on github).

**Comment by KrisSiegel** [comment]
Perhaps if a registry isn't configured we could look in the file system for docker containers at some specified place?

**Comment by ericjperry** [comment]
Yeah that's a good idea, maybe hit the local docker daemon and check what images are installed on the box? Seems like a good idea. Per @sapanshah (in person conversation): "Let's worry about that later". Sounds good to me!
