### ISSUE TITLE
Docker Pull and Login

### ISSUE THREAD

**Issue by sapanshah** [immuta/bakula#47]
Add the ability to do a docker pull and a docker login to the docker agent.

**Comment by ericjperry** [comment]
For docker login, are you just thinking that we provide the username/password when the class is initialized and if they are provided the agent calls login? Just curious on your vision/the details.

**Comment by sapanshah** [comment]
Correct if you provide us a username and password then we will do a docker login in the initialize.

**Comment by ericjperry** [comment]
:+1:

**Comment by KrisSiegel** [comment]
:+1: 

MERGE IT

**Comment by sapanshah** [comment]
Closed by #48
